import Head from "next/head";
import styles from "../styles/Home.module.scss";

import Dashboard from "../components/dashboard";
export default function Home() {
    return (
        <div className={styles.main_container}>
            <Head>
                <title>Frontend Mentor | Time tracking dashboard</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="./images/favicon-32x32.png" />
            </Head>

            <Dashboard />
        </div>
    );
}
